dist: trusty
language: csharp
solution: unit-testing-using-dotnet-test.sln
dotnet: 2.1.502
python: 3.6
jdk:
  - oraclejdk8

branches:
  except:
    - jenkins
  only:
    - travis
    - travis-ci
    - master

script:
  - dotnet restore
  - dotnet tool install dotnet-sonarscanner --tool-path=bin
  - dotnet tool install coverlet.console --tool-path=bin
  - cp ./SonarQube.Analysis.xml ./bin/.store/dotnet-sonarscanner/4.5.0/dotnet-sonarscanner/4.5.0/tools/netcoreapp2.1/any/SonarQube.Analysis.xml
  - cp ./SonarQube.Analysis.xml ./bin/
  - bin/dotnet-sonarscanner begin /k:"timbo:dotnet-code-coverage" #/s:"SonarQube.Analysis.xml"
    #/d:sonar.sources=Calculation,PrimeService\
    #/d:sonar.inclusions=Calculation/Basic/*.cs,PrimeService/PrimeService.cs\
    #/d:sonar.exclusions=Calculation/bin/**/*,Calculation/obj/**/*,PrimeService/bin/**/*,PrimeService/obj/**/*\
    #/d:sonar.tests=CalculationTests,PrimeServiceTests\
    #/d:sonar.test.inclusions=CalculationTests/*.cs,PrimeServiceTests/*.cs\
    #/d:sonar.cs.opencover.reportsPaths=calculation.opencover.xml,prime.opencover.xml\
    #/d:sonar.dotnet.visualstudio.solution.file=unit-testing-using-dotnet-test.sln
  - dotnet build
  - python bin/test_and_report.py
  - bin/dotnet-sonarscanner end
  #- sonar-scanner -Dsonar.verbose=true

addons:
  sonarcloud:
    organization: timbo

