dist: trusty
language: csharp
solution: unit-testing-using-dotnet-test.sln
dotnet: 2.1.502
python: 3.6
script:
  - dotnet restore
  - dotnet tool install coverlet.console --tool-path=bin
  - python test_and_report.py
  - sonar-scanner

addons:
  sonarcloud:
    organization: timbo

