dist: trusty
language: csharp
solution: unit-testing-using-dotnet-test.sln
dotnet: 2.1.502
python: 3.6
jdk:
  - oraclejdk8

script:
  - dotnet restore
  - dotnet tool install dotnet-sonarscanner --tool-path=bin
  - dotnet tool install coverlet.console --tool-path=bin
  - dotnet bin/sonarscanner begin /k:"timbo:dotnet-code-coverage"
  - dotnet build
  - python bin/test_and_report.py
  - dotnet bin/sonarscanner end
  #- sonar-scanner -Dsonar.verbose=true

addons:
  sonarcloud:
    organization: timbo

