dist: trusty
language: csharp
solution: unit-testing-using-dotnet-test.sln
dotnet: 2.1.502
python: 3.6
jdk:
  - oraclejdk8

script:
  - dotnet restore
  - dotnet tool install coverlet.console --tool-path=bin
  - python bin/test_and_report.py
  - sonar-scanner -Dsonar.verbose=true

addons:
  sonarcloud:
    organization: timbo

